name: CI-CD

on:
  push:
    branches: ["master"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and copy files
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.4'

      - name: Install Poetry
        run: pipx install poetry
      
      - name: Install dependencies
        run: poetry install

      - name: Execute tests
        run: poetry run task test
          